[brick]
name="CVI"
version="0.1.0"
chplVersion="2.2.0"
license="None"
type="library"
# TODO: implementation still in progress, use -sSIMD.implementationWarnings=false
compopts="--using-attribute-toolname=lint -sCVI.implementationWarnings=false --no-overload-sets-checks"

# TODO
# "BitTest.chpl"
# "CmpTest.chpl"
# "IterTest.chpl"
tests = [
  "ArrTest.chpl",
  "FmaTest.chpl",
  "InitTest.chpl",
  "MathFuncs.chpl",
  "MathTest.chpl",
  "ShuffleTest.chpl",
  "SqrtTest.chpl"
]

[dependencies]

