[brick]
name="CVL"
version="0.1.0"
author="Jade Abraham"
chplVersion="2.4.0"
license="Apache-2.0"
# TODO: commas inside of strings are broken in Mason
#copyright="2025, Jade Abraham"
copyright="2025; Jade Abraham"
type="library"
compopts="--using-attribute-toolname=lint --no-overload-sets-checks --ccflags=-Wno-strict-prototypes"
docopts="--using-attribute-toolname=lint"

tests = [
  "ArrTest.chpl",
  "BitTest.chpl",
  "Bounds.chpl",
  "BytesTest.chpl",
  "Casting.chpl",
  "CmpTest.chpl",
  "Distributed.chpl",
  "FmaTest.chpl",
  "GatherTest.chpl",
  "InitTest.chpl",
  "IsAllTest.chpl",
  "IterTest.chpl",
  "MaskLoadTest.chpl",
  "MathFuncs.chpl",
  "MathTest.chpl",
  "SAXPYVariants.chpl",
  "Shifts.chpl",
  "ShiftHalts.chpl",
  "ShuffleTest.chpl",
  "SqrtTest.chpl",
  "sleef/Trig.chpl",
]

# TODO: mason libraries don't let you `mason run` examples!
[examples]
examples = [ "SAXPY.chpl" ]

[dependencies]

[architecture]
[architecture.x86_64]
compopts = "--ccflags=-msse4.1 --ccflags=-mavx2 --ccflags=-mfma"
[architecture.arm64]
compopts = "--ccflags=-march=armv8.2-a+fp16"

[tool.chpl-language-server]
module-dir = ["src"]

[tool.chplcheck]
file = ["src/**/*.chpl", "test/**/*.chpl"]
add-rules = ["lint/rules.py"]
disable-rule = ["IncorrectIndentation"]
