[brick]
name="CVL"
version="0.1.0"
chplVersion="2.2.0"
license="None"
type="library"
# TODO: implementation still in progress, use -sSIMD.implementationWarnings=false
compopts="--using-attribute-toolname=lint -sCVL.implementationWarnings=false --no-overload-sets-checks"
docopts="--using-attribute-toolname=lint"

# TODO
# "BitTest.chpl"
# "IterTest.chpl"
tests = [
  "ArrTest.chpl",
  "CmpTest.chpl",
  "FmaTest.chpl",
  "GatherTest.chpl",
  "InitTest.chpl",
  "MaskLoadTest.chpl",
  "MathFuncs.chpl",
  "MathTest.chpl",
  "ShuffleTest.chpl",
  "SqrtTest.chpl"
]

[dependencies]

[architecture]
[architecture.x86_64]
compopts = "--ccflags -msse4.1 --ccflags -mavx2"
[architecture.arm64]
compopts = ""

[tool.chpl-language-server]
module-dir = ["src"]

[tool.chplcheck]
file = ["src/*.chpl"]
add-rules = ["lint/rules.py"]
disable-rule = ["IncorrectIndentation"]
