#!/usr/bin/env python3

import os
import tomllib

workspace = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
Mason_toml = os.path.join(workspace, "Mason.toml")
src = os.path.join(workspace, "src")

with open(Mason_toml, "rb") as f:
  data = tomllib.load(f)

compopts = data["brick"].get("compopts", "")
print(f"-M{src} {compopts}")
