name: benchmarks
on:
  workflow_call:
    inputs:
      chapel_version:
        description: 'Chapel version to use (latest, nightly, or a specific version)'
        required: true
        type: string

jobs:

  # this just runs the benchmarks to make sure they compile and run
  test-benchmarks:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        backend: [llvm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python Dependencies
        run: |
          python3 -m venv .venv
          ./.venv/bin/python3 -m pip install --upgrade pip
          ./.venv/bin/python3 -m pip install pydantic
      - name: Setup chapel
        uses: jabraham17/setup-chpl@main
        with:
          version: ${{ inputs.chapel_version }}
          backend: ${{ matrix.backend }}
      - name: Setup fortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 15
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build CVL
        run: |
          mason build
      - name: Run Benchmarks
        run: |
          source util/localRegistry.sh
          ./.venv/bin/python3 ./util/bench.py \
            --schema benchmarks/benchmarks.json \
            --trials 3 --small
