name: chpl tests
on:
  workflow_call:
    inputs:
      chapel_version:
        description: 'Chapel version to use (latest, nightly, or a specific version)'
        required: true
        type: string
      run_optional_tests:
        description: 'Whether to run additional tests (Python)'
        required: false
        type: boolean
        default: true

# brew only supports nightly and latest
jobs:
  mason-test-linux-x86:
    if: ${{ inputs.chapel_version == 'nightly' || inputs.chapel_version == 'latest' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - llvm
          - gnu
    env:
      CHPL_TARGET_COMPILER: ${{ matrix.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Chapel
        run: |
          if [ "${{ inputs.chapel_version }}" = "nightly" ]; then
            brew install --HEAD chapel
          else
            brew install chapel
          fi
      - name: Run Tests
        run: |
          ./util/test.sh

  mason-test-linux-arm:
    if: ${{ inputs.chapel_version == 'nightly' || inputs.chapel_version == 'latest' }}
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        backend:
          - llvm
          - gnu
    env:
      CHPL_TARGET_COMPILER: ${{ matrix.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Chapel
        run: |
          if [ "${{ inputs.chapel_version }}" = "nightly" ]; then
            brew install --HEAD chapel
          else
            brew install chapel
          fi
      - name: Run Tests
        run: |
          ./util/test.sh

  # brew only supports nightly and latest
  mason-test-macos-arm:
    if: ${{ inputs.chapel_version == 'nightly' || inputs.chapel_version == 'latest' }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        backend:
          - llvm
          - clang
    env:
      CHPL_TARGET_COMPILER: ${{ matrix.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Chapel
        run: |
          if [ "${{ inputs.chapel_version }}" = "nightly" ]; then
            brew install --HEAD chapel
          else
            brew install chapel
          fi
      - name: Run Tests
        run: |
          ./util/test.sh

  mason-test-docker:
    strategy:
      fail-fast: false
      matrix:
        image:
          - chapel/chapel:${{ inputs.chapel_version }}
          - chapel/chapel-gasnet:${{ inputs.chapel_version }}
          - chapel/chapel-gasnet-smp:${{ inputs.chapel_version }}
        backend:
          - llvm
          - gnu
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    env:
      CHPL_TARGET_COMPILER: ${{ matrix.backend }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
      - name: Run Tests
        run: |
          ./util/test.sh
      - name: Run CMake Tests
        run: |
          ./util/testCMake.sh

  lint:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:${{ inputs.chapel_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run lints
        run: |
          ./util/lint.sh

  python-tests:
    if: ${{ inputs.run_optional_tests }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install tox
      - name: Run Python Tests
        run: |
          ./util/tox.sh
