name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mason-test-linux-x86:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run `mason test`
        run: |
          mason test --parallel --show
  mason-test-macos-arm:
    runs-on: macos-latest
    container:
      image: chapel/chapel:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run `mason test`
        run: |
          mason test --parallel --show
  chplcheck:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run chplcheck
        run: |
          set -x
          ./lint.sh
