name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

# TODO: add a linux-arm runner

jobs:
  mason-test-linux-x86:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          ./test.sh
  mason-test-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Chapel
        run: |
          brew install chapel
      - name: Run Tests
        run: |
          ./test.sh
  chplcheck:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run chplcheck
        run: |
          set -x
          ./lint.sh
