name: CI
#
# Runs tests on every push to the main branch
#
on:
  push:
    branches:
      - main
  workflow_dispatch:

# TODO: add a linux-arm runner

# TODO: add comm!=none jobs for brew once brew has ML chapel

jobs:
  test-chpl-latest:
    uses: ./.github/workflows/chpl-test.yml
    with:
      chapel_version: latest
      run_optional_tests: true
  test-chpl-2.4:
    uses: ./.github/workflows/chpl-test.yml
    with:
      chapel_version: 2.4.0
      run_optional_tests: false
