name: CI
#
# Runs tests on every push to the main branch
#
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

# TODO: add comm!=none jobs for brew once brew has ML chapel

# TODO: add auto benchmarks for https://github.com/benchmark-action/github-action-benchmark

jobs:
  test-chpl-latest:
    uses: ./.github/workflows/chpl-tests.yml
    with:
      chapel_version: latest
      run_optional_tests: true
  # test-chpl-2_4:
  #   uses: ./.github/workflows/chpl-tests.yml
  #   with:
  #     chapel_version: 2.4.0
  #     run_optional_tests: false
