name: Run on chpl nightly
#
# Runs the same tests as the CI, but using the latest Chapel nightly build.
# This prevents potential regressions from the latest changes in Chapel. This
# workflow runs on a weekly schedule and can also be triggered manually.
#
# This workflow also tests a couple of specific older Chapel versions to
# ensure compatibility.
#

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 UTC every Sunday
  workflow_dispatch:

jobs:
  test-chpl-nightly:
    uses: ./.github/workflows/chpl-tests.yml
    with:
      chapel_version: nightly
      run_optional_tests: false
  test-chpl-2_6_0:
    uses: ./.github/workflows/chpl-tests.yml
    with:
      chapel_version: 2.6.0
      run_optional_tests: false
  test-chpl-2_5_0:
    uses: ./.github/workflows/chpl-tests.yml
    with:
      chapel_version: 2.5.0
      run_optional_tests: false
