name: Run on Chapel nightly
#
# Runs the same tests as the CI, but using the latest Chapel nightly build.
# This prevents potential regressions from the latest changes in Chapel. This
# workflow runs on a weekly schedule and can also be triggered manually.
#

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 UTC every Sunday
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/chapel-test.yml
    with:
      chapel_version: nightly
      run_optional_tests: false
