name: Run on Chapel nightly
#
# Runs the same tests as the CI, but using the latest Chapel nightly build.
# This prevents potential regressions from the latest changes in Chapel. This
# workflow runs on a weekly schedule and can also be triggered manually.
#

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 UTC every Sunday
  workflow_dispatch:

jobs:
  nightly-mason-test-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Chapel from HEAD
        run: |
          brew install --HEAD chapel
      - name: Run Tests
        run: |
          ./test.sh

  nightly-mason-test-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Chapel from HEAD
        run: |

          brew install --HEAD chapel
      - name: Run Tests
        run: |
          ./test.sh

  nightly-chplcheck:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run chplcheck
        run: |
          ./lint.sh
